### PR TITLE
Added support for custom OIDC providers to set up authentication #92

### PR DESCRIPTION
**Pull request by kamtschatka**
Added support for custom OIDC providers to set up authentication

I tried it with Google and Authentik and it worked great.
Only thing missing is showing the error message in "apps/web/components/signin/SignInForm.tsx", but I failed to do so, since it is a server side rendered component and I was not able to get the "error" parameter from the querystring and show it on screen.

### CODE REVIEW

**Comment by winston0410** [comment]
I want to manage my account in Hoarder through OIDC as well, and this PR looks good. Do we know what is blocking this PR?

**Comment by MohamedBassem** [comment]
@winston0410 Nothing is blocking this PR except me being a little busy. I have some local improvements that I need to push to this PR before merging it but still hadn't got a chance to do so. Sorry about that.

**Comment by mikevanes** [comment]
Any news on the progress on this PR, would love to see it integrated so I can use Authentik.

**Comment by MohamedBassem** [comment]
@mikevanes I'll be merging it hopefully tomorrow. Again sorry about the delay.

**Comment by MohamedBassem** [comment]
@kamtschatka To keep this PR simple, I reverted the extension changes from this PR. You (or I can do it) send it in a separate PR after we land this one. I also did some minor changes to the decision or whether the user is an admin or not.
I'll test those changes now against my authentik setup, and if it works, I'll merge the PR.

**Comment by MohamedBassem** [comment]
Found a bug in the drizzle adapter definition that was preventing the correct propagation of the role from the profile to the database. Fixed in (https://github.com/hoarder-app/hoarder/commit/80749d5327942c12b513124c43e3577fdd8c0541). Testing one more time.

**Comment by MohamedBassem** [comment]
Tested it and works flawlessly! Thanks a lot @kamtschatka (as usual) and I'm really really sorry for how long it took me to get to this PR. This is one of the most requested features :) It'll be available in the next release!

**Comment by mikevanes** [comment]
Thank you for the effort @MohamedBassem and @kamtschatka looking forward to the feature!

**Pull request merged**
