### PR TITLE
add Arch Linux installation

### PR DESCRIPTION
**Pull request by devome**
add Arch Linux installation

### CODE REVIEW

**Comment by MohamedBassem** [comment]
Oh wow, that I didn't see coming :) Thanks a lot for submitting this to arch's registry. Pardon my ignorance with the arch model, but I'm wondering, what's the maintenance model here? For example, with version updates, is it going to be on you to notice that there's a version upgrade an update the arch package? Same with new package dependencies, etc? Does the arch registry accept PRs (or whatever they are called there) from people other than the maintainer?

As for the PR itself, I'll have a look on the PKGBUILD file and merge afterwards :)

**Comment by devome** [comment]
If Hoarder has an update, the package on AUR will also be updated automatically by my [nvcheck](https://github.com/lilydjwg/nvchecker) scripts. If there is a change in dependency, I usually notice it, or other users will remind me to add it when they notice it. 

AUR can add co-maintainers and maintain packages together. If you are willing to participate in the maintenance work of `hoarder` on AUR, I can add you as a co-maintainer.

**Comment by MohamedBassem** [comment]
Thanks a lot for your effort adding Hoarder to arch. I'm not an arch user myself, but if you need any help maintaining the package, please let me know and I'd be happy to help :)

**Comment by devome** [comment]
@MohamedBassem That's OK, thank you.

**Pull request merged**
