### PR TITLE
fix dead installation link

### PR DESCRIPTION
**Pull request by disappointingsupernova**

### CODE REVIEW

**Comment by disappointingsupernova** [comment]
The installation link in the README is dead. A capitalised I in Installation

**Comment by MohamedBassem** [comment]
hmmm, the link in the readme works fine for me

**Comment by kamtschatka** [comment]
yeah works for me as well, but technically, with the uppercase it returns status code 200, with lowercase you get status code 404 and it works itself out somehow. 
So since the PR is already up, I would just merge it, it is definitely correct.

**Comment by MohamedBassem** [comment]
Oh, the 404 is surprising.

**Pull request merged**
