### PR TITLE
[Bug Report] Importing bookmarks adds all tags to all bookmarks #421

### PR DESCRIPTION
**Pull request by kamtschatka**
fixed an issue that caused all existing tags to be assigned to a new bookmark

### CODE REVIEW

**Comment by MohamedBassem** [comment]
Oh, that's an ugly bug. I think I'll have to cut a hotfix for this one.

**Comment by MohamedBassem** [comment]
I think if the user is passing an object with both `tagName` and `tagId` as empty, then the request is invalid. Let me change the check to be a zod validation instead.

**Comment by kamtschatka** [comment]
but that will show up as a lot of errors then? 
you'll at least have to prevent it on the client side as well, or not?

**Comment by MohamedBassem** [comment]
@kamtschatka Yeah, I found the bug in the client side. Apparently I fixed it for Pocket but not for the netscape importer.

**Comment by MohamedBassem** [comment]
The frontend fix: https://github.com/hoarder-app/hoarder/commit/4db50c234fb0da8747b902a7c1e551cc54451f4c

**Pull request merged**
