### PR TITLE
New WebUI alpha

### PR DESCRIPTION
**Pull request by redoracle**
# Pull Request Proposal: Web UI Improvements for Hoarder

## Summary

This proposal introduces several key enhancements to the Web UI of the Hoarder project to improve user experience, responsiveness, and visual appeal.

## Changes Proposed

1. **Collapsible Sidebar**: The sidebar can now be collapsed by clicking on the logo, providing a cleaner interface and more screen space for content.
2. **Streamlined Menu**: The menu has been redesigned to be more synthetic and user-friendly.
3. **Enhanced Responsiveness**: Improved responsiveness across various devices for a seamless user experience.
4. **Improved Color Scheme**: Updated the color scheme to be more aesthetically pleasing and consistent with modern design standards.
5. **YouTube Play Symbol on Video Cards**: Added a YouTube play symbol to video cards for better visual cues and user interaction.
6. **Extended Card Grid**: The card grid has been extended to accommodate more content and improve layout flexibility.

These improvements aim to enhance the overall usability and visual appeal of the Hoarder Web UI.

## Detailed Changes

- **Collapsible Sidebar**:
  - Clicking on the Hoarder logo will now collapse or expand the sidebar.
  - Provides a more spacious interface when the sidebar is not in use.
  
- **Streamlined Menu**:
  - Redesigned the menu for a more intuitive and synthetic navigation experience.
  - Grouped related items together for easier access.

- **Enhanced Responsiveness**:
  - Improved layout and components to ensure they adapt smoothly to different screen sizes and orientations.
  - Ensured all elements are touch-friendly for mobile devices.

- **Improved Color Scheme**:
  - Updated the color palette for better contrast and readability.
  - Consistent use of colors to highlight important actions and statuses.

- **YouTube Play Symbol on Video Cards**:
  - Added a recognizable play symbol on video thumbnails.
  - Helps users quickly identify video content and encourages interaction.

- **Extended Card Grid**:
  - Expanded the card grid layout to display more items at once.
  - Optimized spacing and alignment for a cleaner look.

These changes aim to provide a more modern, user-friendly, and visually appealing interface for the Hoarder Web UI. Feedback and suggestions are welcome to further refine these improvements.

Screenshot 2024-07-29 at 18 20 30
Screenshot 2024-07-29 at 18 20 11
Screenshot 2024-07-29 at 18 15 58
Screenshot 2024-07-29 at 18 16 16
Screenshot 2024-07-29 at 18 16 41
Screenshot 2024-07-29 at 18 16 59
Screenshot 2024-07-29 at 18 17 21
Screenshot 2024-07-29 at 18 17 39

### CODE REVIEW

**Comment by redoracle** [comment]
Tnx all for maintaining this repo. This is my humble contribute.

**Comment by MohamedBassem** [comment]
@redoracle I'm really really sorry it took me that long to get back to you on this PR. I really appreciate the effort you put into building this new UI. However, I think for such a big change, it might have been better if we align together (in the #development discord channel) about what we want to achieve before putting such a large effort into a big redesign to make sure your effort is not wasted.
You have some good ideas in the redesign (such as the collapsable side panel) but there are some rough edges in the design as well (some of the background colors for the bookmark grid being one example and the alignment of the lists in the sidebar with the rest of the sidebar items).
I'm going to close this PR right now (unfortunately), but we'd be more happy to discuss with you on discord some specific areas where you can help on the UI side :)

**Comment by redoracle** [comment]
Hi Mohamed,

Many thanks for your comment.

Tbh that was a quick proposal to improve the UI, did not mean to be
definitive, was just a prototype that needed fine tuning and of course was
open to changes and suggestions.

Please share the discord invite , I couldn't find the discord link on the
website nor GitHub.

Regards

**Comment by kamtschatka** [comment]
haha, i had the same issue. it is in the readme (first line with the build and release stuff). It is an image with a link and not a real link:
image

**Comment by redoracle** [comment]
Hehe... Maybe advertising it more could help the  growth of the community :)

**Comment by redoracle** [comment]
Thanks

**Pull request closed without merging**
